---
Name: customroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'search/$ID' : 'Search_Controller'
    'competitions': 'ChallengeController'
    'v': 'VideoController'
    'upload': 'UploadController'